BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "raven-bsp"
BBFILE_PATTERN_raven-bsp := "^${LAYERDIR}/"
BBFILE_PRIORITY_raven-bsp = "20"
LAYERSERIES_COMPAT_raven-bsp = "wrynose"
LAYERDEPENDS_raven-bsp = "core fsl-bsp-release"
