BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "raven"
BBFILE_PATTERN_raven := "^${LAYERDIR}/"
BBFILE_PRIORITY_raven = "20"
LAYERSERIES_COMPAT_raven = "wrynose"
LAYERDEPENDS_raven = "core fsl-bsp-release fsl-sdk-release ros-common-layer ros2-layer ros2-jazzy-layer"
