# Shared Raven policy, using NXP's common i.MX distro settings.
require conf/distro/include/fsl-imx-base.inc
DISTRO = "raven"
DISTRO_NAME = "Raven Linux"
DISTROOVERRIDES:append = ":raven"
DISTRO_FEATURES:remove = "x11 wayland opengl vulkan"
