BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "raven-sdk"
BBFILE_PATTERN_raven-sdk := "^${LAYERDIR}/"
BBFILE_PRIORITY_raven-sdk = "20"
LAYERSERIES_COMPAT_raven-sdk = "wrynose"
LAYERDEPENDS_raven-sdk = "core raven-bsp fsl-sdk-release ros-common-layer ros2-layer ros2-jazzy-layer"
