#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Source this script from the repo workspace, as with NXP's setup script.
_raven_setup_release() {
    local raven_root raven_workspace raven_machine raven_distro raven_build_dir
    local raven_eula raven_existing_machine raven_status raven_arg
    raven_root=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd) || return 1
    raven_workspace=$(cd "$raven_root/../.." && pwd) || return 1
    raven_machine=${MACHINE:-raven-frdm-imx95}
    raven_distro=${DISTRO:-raven}
    raven_build_dir="build-$raven_machine"
    while (( $# )); do
        case "$1" in
            -b) [[ $# -ge 2 ]] || { echo "Missing build directory" >&2; return 1; }
                raven_build_dir=$2; shift 2 ;;
            -h|--help)
                echo "MACHINE=<board> DISTRO=<distro> source raven-setup-release.sh [-b build-directory]"
                echo "Default machine: raven-frdm-imx95; default distro: raven"
                return 0 ;;
            *) echo "Unknown argument: $1" >&2; return 1 ;;
        esac
    done
    [[ $raven_machine =~ ^[a-zA-Z0-9_-]+$ && $raven_distro =~ ^[a-zA-Z0-9_-]+$ ]] || {
        echo "Invalid machine or distro name" >&2; return 1;
    }
    [[ -f "$raven_root/meta-raven-bsp/conf/machine/$raven_machine.conf" ||
       -f "$raven_workspace/sources/meta-imx/meta-imx-bsp/conf/machine/$raven_machine.conf" ]] || {
        echo "Unknown machine: $raven_machine" >&2; return 1;
    }
    [[ -f "$raven_root/meta-raven-sdk/conf/distro/$raven_distro.conf" ||
       -f "$raven_workspace/sources/meta-imx/meta-imx-sdk/conf/distro/$raven_distro.conf" ]] || {
        echo "Unknown distro: $raven_distro" >&2; return 1;
    }
    [[ $raven_build_dir = /* ]] || raven_build_dir="$raven_workspace/$raven_build_dir"
    raven_build_dir=$(realpath -m "$raven_build_dir") || return 1
    if [[ -f "$raven_build_dir/conf/local.conf" && ! -f "$raven_build_dir/conf/raven.conf" ]]; then
        echo "Use a new build directory; this directory was configured by another setup." >&2
        return 1
    fi
    if [[ -f "$raven_build_dir/conf/raven.conf" ]]; then
        raven_existing_machine=$(sed -n 's/^MACHINE = "\([^" ]*\)"$/\1/p' "$raven_build_dir/conf/raven.conf")
        [[ $raven_existing_machine == "$raven_machine" ]] || {
            echo "Build directory belongs to $raven_existing_machine; select another directory." >&2
            return 1
        }
    fi
    raven_eula=${ACCEPT_FSL_EULA:-0}
    [[ $raven_eula == 0 || $raven_eula == 1 ]] || {
        echo "ACCEPT_FSL_EULA must be 0 or 1" >&2; return 1;
    }
    export TEMPLATECONF="$raven_root/meta-raven-sdk/conf/templates/default"
    source "$raven_workspace/sources/openembedded-core/oe-init-build-env" "$raven_build_dir"
    raven_status=$?
    (( raven_status == 0 )) || return "$raven_status"
    cat > conf/raven.conf <<EOF
# Generated by raven-setup-release.sh; put additional settings in local.conf.
MACHINE = "$raven_machine"
DISTRO = "$raven_distro"
SDKMACHINE = "x86_64"
ACCEPT_FSL_EULA = "$raven_eula"
EOF
    "${REPO:-$HOME/bin/repo}" manifest -r -o "$PWD/resolved-manifest.xml" || return 1
    echo "Raven setup complete: MACHINE=$raven_machine DISTRO=$raven_distro"
    echo "Build directory: $PWD. No compilation started."
}
_raven_setup_release "$@"
