#!/usr/bin/env bash
#
# Raven adaptation of NXP Robotics Edge v1.0.0 environment setup.
# Copyright 2025 NXP
# Copyright 2026 Swamy BV
#
# Source this script from the repo workspace, as with NXP's setup script.
_raven_setup_release() {
    local raven_root raven_workspace raven_machine raven_distro raven_build_dir
    local raven_eula raven_existing_machine raven_status
    local ROS2_DISTRO=${ROS2_DISTRO:-jazzy}
    local OPTIND=1 nxp_setup_flag
    raven_root=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd) || return 1
    raven_workspace=$(cd "$raven_root/../.." && pwd) || return 1
    raven_machine=${MACHINE:-raven-frdm-imx95}
    raven_distro=${DISTRO:-raven}
    raven_build_dir="build-$raven_machine"
    # NXP-style command-line options: build directory and ROS distro.
    while getopts ":b:r:h" nxp_setup_flag; do
        case "$nxp_setup_flag" in
            b) raven_build_dir=$OPTARG ;;
            r) ROS2_DISTRO=$OPTARG ;;
            h)
                echo "MACHINE=<board> DISTRO=<distro> source raven-setup-release.sh [-b build-directory] [-r jazzy]"
                echo "Default machine: raven-frdm-imx95; default distro: raven"
                return 0 ;;
            :) echo "Missing argument for -$OPTARG" >&2; return 1 ;;
            *) echo "Unknown option: -$OPTARG" >&2; return 1 ;;
        esac
    done
    shift $((OPTIND - 1))
    (( $# == 0 )) || { echo "Unexpected arguments: $*" >&2; return 1; }
    [[ $ROS2_DISTRO == jazzy ]] || {
        echo "Only ROS 2 Jazzy is configured in the current Raven SDK layer." >&2
        return 1
    }
    [[ $raven_machine =~ ^[a-zA-Z0-9_-]+$ && $raven_distro =~ ^[a-zA-Z0-9_-]+$ ]] || {
        echo "Invalid machine or distro name" >&2; return 1;
    }
    [[ -f "$raven_root/meta-raven-bsp/conf/machine/$raven_machine.conf" ||
       -f "$raven_workspace/sources/meta-imx/meta-imx-bsp/conf/machine/$raven_machine.conf" ]] || {
        echo "Unknown machine: $raven_machine" >&2; return 1;
    }
    [[ -f "$raven_root/meta-raven-sdk/conf/distro/$raven_distro.conf" ||
       -f "$raven_workspace/sources/meta-imx/meta-imx-sdk/conf/distro/$raven_distro.conf" ]] || {
        echo "Unknown distro: $raven_distro" >&2; return 1;
    }
    [[ $raven_build_dir = /* ]] || raven_build_dir="$raven_workspace/$raven_build_dir"
    raven_build_dir=$(realpath -m "$raven_build_dir") || return 1
    if [[ -f "$raven_build_dir/conf/local.conf" && ! -f "$raven_build_dir/conf/raven.conf" ]]; then
        echo "Use a new build directory; this directory was configured by another setup." >&2
        return 1
    fi
    if [[ -f "$raven_build_dir/conf/raven.conf" ]]; then
        raven_existing_machine=$(sed -n 's/^MACHINE = "\([^" ]*\)"$/\1/p' "$raven_build_dir/conf/raven.conf")
        [[ $raven_existing_machine == "$raven_machine" ]] || {
            echo "Build directory belongs to $raven_existing_machine; select another directory." >&2
            return 1
        }
    fi
    raven_eula=${ACCEPT_FSL_EULA:-0}
    [[ $raven_eula == 0 || $raven_eula == 1 ]] || {
        echo "ACCEPT_FSL_EULA must be 0 or 1" >&2; return 1;
    }
    export TEMPLATECONF="$raven_root/meta-raven-sdk/conf/templates/default"
    source "$raven_workspace/sources/openembedded-core/oe-init-build-env" "$raven_build_dir"
    raven_status=$?
    (( raven_status == 0 )) || return "$raven_status"
    cat > conf/raven.conf <<EOF
# Generated by raven-setup-release.sh; put additional settings in local.conf.
MACHINE = "$raven_machine"
DISTRO = "$raven_distro"
SDKMACHINE = "x86_64"
ROS_DISTRO = "$ROS2_DISTRO"
ACCEPT_FSL_EULA = "$raven_eula"
EOF
    (cd "$raven_workspace" && "${REPO:-$HOME/bin/repo}" manifest -r -o "$raven_build_dir/resolved-manifest.xml") || return 1
    echo "Raven setup complete: MACHINE=$raven_machine DISTRO=$raven_distro"
    echo "Build directory: $PWD. No compilation started."
    echo "To return: MACHINE=$raven_machine DISTRO=$raven_distro source $raven_workspace/raven-setup-release.sh -b $raven_build_dir -r $ROS2_DISTRO"
}
_raven_setup_release "$@"
